name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le site
        uses: actions/checkout@v4

      - name: Publier sur Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEILOUY_NICHMAT_MMEAZOGUI }}"
          channelId: live
          projectId: leilouy-nichmat-mmeazogui
